parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"ceUA":[function(require,module,exports) {
"use strict";function r(r,o){if(!(r instanceof o))throw new TypeError("Cannot call a class as a function")}function o(r,o){for(var e=0;e<o.length;e++){var t=o[e];t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(r,t.key,t)}}function e(r,e,t){return e&&o(r.prototype,e),t&&o(r,t),r}Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var t=function(){function o(){r(this,o),this._usernameBackgroundColor="",this._usernames=[],this._usernamesAreRegExp=!1,this._moderatorBackgroundColor="",this._initialBackgroundColor="",this._chatListFunc=function(){return[]},this._loaded=!1,this._defaultUsernameBackgroundColor="",this._defaultModeratorBackgroundColor=""}return e(o,[{key:"loadedChatList",value:function(){this._loaded=!0}},{key:"fetchedConfig",set:function(r){this._usernameBackgroundColor=r.usernameBackgroundColor||this._usernameBackgroundColor||this._defaultUsernameBackgroundColor,this._usernames=r.usernames||this._usernames,this._usernamesAreRegExp=r.usernamesAreRegExp||this._usernamesAreRegExp,this._moderatorBackgroundColor=r.moderatorBackgroundColor||this._moderatorBackgroundColor||this._defaultModeratorBackgroundColor}},{key:"colors",get:function(){return{username:this._usernameBackgroundColor,moderator:this._moderatorBackgroundColor,initialBackgroundColor:this._initialBackgroundColor}}},{key:"usernameBackgroundColor",get:function(){return this._usernameBackgroundColor}},{key:"usernames",get:function(){return this._usernames}},{key:"usernamesAreRegExp",get:function(){return this._usernamesAreRegExp}},{key:"moderatorBackgroundColor",get:function(){return this._moderatorBackgroundColor}},{key:"loaded",get:function(){return this._loaded}},{key:"initialBackgroundColor",get:function(){return this._initialBackgroundColor},set:function(r){""===this._initialBackgroundColor&&(this._initialBackgroundColor=r)}},{key:"chatListFunc",get:function(){return this._chatListFunc||function(){return[]}},set:function(r){0===this._chatListFunc.length&&(this._chatListFunc=r)}},{key:"defaultColor",set:function(r){this._defaultUsernameBackgroundColor=r.usernameBackgroundColor,this._defaultModeratorBackgroundColor=r.moderatorBackgroundColor}}]),o}(),n=new t;exports.default=n;
},{}],"xdg2":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.configKeys=void 0;var e={usernamesKeyName:"usernamesKeyName",usernamesAreRegExpKeyName:"usernamesAreRegExpKeyName"};exports.configKeys=e;
},{}],"Ck9U":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.chatListFunc=exports.configKeys=exports.isUsername=exports.isModerator=void 0;var e=require("./common-const"),r=function(e){return"moderator"===e.getAttribute("author-type")};exports.isModerator=r;var t=function(e,r){var t=e.querySelector("#author-name");if(!t)return!1;var o=t.textContent;if(!r.usernamesAreRegExp)return r.usernames.some(function(e){return o.includes(e)});try{return r.usernames.some(function(e){return new RegExp(e).test(o)})}catch(n){return!1}};exports.isUsername=t;var o={usernameBackgroundColorKeyName:"gaming_usernameBackgroundColorKeyName",usernamesKeyName:e.configKeys.usernamesKeyName,usernamesAreRegExpKeyName:e.configKeys.usernamesAreRegExpKeyName,moderatorBackgroundColorKeyName:"gaming_moderatorBackgroundColorKeyName"};exports.configKeys=o;var n=function(){return document.querySelector("yt-live-chat-renderer yt-live-chat-item-list-renderer #items")};exports.chatListFunc=n;
},{"./common-const":"xdg2"}],"De4i":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("../state"));function t(e){return e&&e.__esModule?e:{default:e}}var o=function(t,o,r){return o(t)?e.default.colors.moderator:r(t,e.default)?e.default.colors.username:e.default.colors.initialBackgroundColor},r=function(e,t,r){return setTimeout(e.forEach(function(e){e.style.backgroundColor=o(e,t,r)}),10)},u=r;exports.default=u;
},{"../state":"ceUA"}],"SIAn":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=r(require("./paint")),t=r(require("../state"));function r(e){return e&&e.__esModule?e:{default:e}}var u=function(r,u){if(t.default.loaded){var a=t.default.chatListFunc().querySelectorAll("yt-live-chat-text-message-renderer");(0,e.default)(a,r,u)}},a=u;exports.default=a;
},{"./paint":"De4i","../state":"ceUA"}],"OhDo":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=r(require("../state"));function r(e){return e&&e.__esModule?e:{default:e}}var o=function(r){return new Promise(function(o,a){var u=r.usernameBackgroundColorKeyName,t=r.usernamesKeyName,n=r.usernamesAreRegExpKeyName,s=r.moderatorBackgroundColorKeyName;chrome.storage.sync.get([u,t,n,s],function(r){e.default.fetchedConfig={usernameBackgroundColor:r[u],usernames:r[t],usernamesAreRegExp:r[n],moderatorBackgroundColor:r[s]},o(e.default)})})},a=o;exports.default=a;
},{"../state":"ceUA"}],"OMhS":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("./fetchConfigColors"));function t(e){return e&&e.__esModule?e:{default:e}}var n=[],r=null,o=function(e,t){n.push(t),r=e};chrome.runtime.onMessage.addListener(function(t,o,u){"save"===t.command&&(0,e.default)(r).then(function(){n.forEach(function(e){return e()})})});var u=o;exports.default=u;
},{"./fetchConfigColors":"OhDo"}],"mbGO":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var t=o(require("./paint")),e=o(require("../state")),r=o(require("./paintAllChats")),n=o(require("./configListener")),a=o(require("./fetchConfigColors"));function o(t){return t&&t.__esModule?t:{default:t}}function u(t){return f(t)||l(t)||i()}function i(){throw new TypeError("Invalid attempt to spread non-iterable instance")}function l(t){if(Symbol.iterator in Object(t)||"[object Arguments]"===Object.prototype.toString.call(t))return Array.from(t)}function f(t){if(Array.isArray(t)){for(var e=0,r=new Array(t.length);e<t.length;e++)r[e]=t[e];return r}}var d=function(o,i,l){var f=setInterval(function(){var d=e.default.chatListFunc();d&&(e.default.initialBackgroundColor=getComputedStyle(d).backgroundColor,(0,a.default)(o).then(function(){new MutationObserver(function(e){var r=e.flatMap(function(t){return u(t.addedNodes)});(0,t.default)(r,i,l)}).observe(d,{childList:!0}),(0,n.default)(o,function(){return(0,r.default)(i,l)}),(0,r.default)(i,l)}),clearInterval(f),e.default.loadedChatList())},500)},c=d;exports.default=c;
},{"./paint":"De4i","../state":"ceUA","./paintAllChats":"SIAn","./configListener":"OMhS","./fetchConfigColors":"OhDo"}],"WMZ8":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e={www:{usernameBackgroundColor:"#ffdddd",moderatorBackgroundColor:"#ddddff"},gaming:{usernameBackgroundColor:"#460f0f",moderatorBackgroundColor:"#192d50"},common:{usernames:[],usernamesAreRegExp:!1}},o=e;exports.default=o;
},{}],"EAB9":[function(require,module,exports) {
"use strict";var e=i(require("./state")),t=require("./gaming-const"),u=i(require("./modules/initialize")),a=i(require("./default-values"));function i(e){return e&&e.__esModule?e:{default:e}}e.default.chatListFunc=t.chatListFunc,e.default.defaultColor=a.default.gaming,(0,u.default)(t.configKeys,t.isModerator,t.isUsername);
},{"./state":"ceUA","./gaming-const":"Ck9U","./modules/initialize":"mbGO","./default-values":"WMZ8"}]},{},["EAB9"], null)